# Generated by Django 4.2.5 on 2023-10-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Matricula', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Curso', models.CharField(max_length=100)),
            ],
        ),
    ]
